volumes:
  vol-postgres:
networks:
  net-db:

services:
  leanchat:
    image: ghcr.io/starnuik/golang_leanchat:latest
    ports: [ 3000:3000, ]
    networks: [ net-db, ]
    restart: on-failure:5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: leanchat
  postgres:
    image: postgres
    networks: [ net-db, ]
    volumes: [ vol-postgres:/var/lib/postgresql/data, ]
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: leanchat

